### ISSUE TITLE
Datset

### ISSUE THREAD

**Issue by eric612** [eric612/Vehicle-Detection#2]
I can not open the dataset , but I can send the download link to you  privately. 
You can leave your email below

Note : Do not use in commercial

**Comment by bangdaibin** [comment]
Can you send me the dataset? Email: quoctran123457y@gmail.com. Thanks

**Comment by OceanWong1991** [comment]
Hi eric612!
   Thx for your contribution for open source project! I use the kitti data set to train yolo_v3 tiny, but the result is not good enough, Can you send the download link to me？ @eric612 Thx again! OceanWong1991@gmail.com

**Comment by AbdeslemSmahi** [comment]
Hello,
Can you please send the dataset link to me? ssnitra20@gmail.com

**Comment by alenweiru** [comment]
Can you send me the dataset? Email: alen.wr.chen@gmail.com. Thanks
